apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: golang-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/niladrix719/QXRsYW4-
    path: charts/backend
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: qxrsyw4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
