apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vue-service 
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/niladrix719/QXRsYW4-
    targetRevision: main
    path: charts/frontend
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: qxrsyw4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
